//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammEasy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class myEntities : DbContext
    {
        public static myEntities my01;
        public myEntities()
            : base("name=myEntities")
        {
        }
    public static myEntities GetContext()
        {
            if (my01 == null)
            {
                my01 = new myEntities();
            }
            return my01;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupUser> GroupUser { get; set; }
        public virtual DbSet<ImgFoto> ImgFoto { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<RoleUser> RoleUser { get; set; }
        public virtual DbSet<ScoreImage> ScoreImage { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
