//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammEasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int IdUser { get; set; }
        public int IdStatus { get; set; }
        public string Description { get; set; }
        public string Foto { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
