//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammEasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TichGroup
    {
        public int Id { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdTicher { get; set; }
    
        public virtual GroupUser GroupUser { get; set; }
        public virtual User User { get; set; }
    }
}
